name: NEST_train
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - accelerate=1.0.1
  - aiosignal=1.3.1
  - arrow-cpp=16.1.0
  - aws-c-auth=0.6.21
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.27
  - aws-c-io=0.13.11
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.2.1
  - aws-c-sdkutils=0.1.7
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - blas=1.0
  - boost-cpp=1.78.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.31
  - colorama=0.4.6
  - cpuonly=2.0
  - dill=0.3.8
  - et_xmlfile=1.1.0
  - freetype=2.12.1
  - fsspec=2024.9.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.5.0
  - gmpy2=2.1.2
  - huggingface_hub=0.26.5
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.11.1
  - libdeflate=1.22
  - libevent=2.1.12
  - libffi=3.4.4
  - libgrpc=1.62.2
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxgboost=2.1.1
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - multiprocess=0.70.16
  - networkx=3.1
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.4.0
  - orc=2.0.1
  - packaging=24.2
  - pandas=2.0.3
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=4.3.6
  - pooch=1.8.2
  - py-xgboost=2.1.1
  - pysocks=1.7.1
  - python=3.8.20
  - python-xxhash=3.5.0
  - python_abi=3.8
  - pytorch=2.4.1
  - pytorch-mutex=1.0
  - pytz=2024.2
  - pyyaml=6.0.2
  - re2=2022.04.01
  - requests=2.32.3
  - scikit-learn=1.3.2
  - setuptools=75.1.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - torchaudio=2.4.1
  - torchvision=0.20.0
  - tqdm=4.67.1
  - transformers=4.46.3
  - ucrt=10.0.22621.0
  - urllib3=2.2.3
  - utf8proc=2.6.1
  - vc=14.40
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - xgboost=2.1.1
  - xxhash=0.8.2
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==24.3.0
      - backcall==0.2.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - click==8.1.8
      - comm==0.2.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - datasets==3.1.0
      - debugpy==1.8.12
      - decorator==5.1.1
      - evaluate==0.4.3
      - executing==2.1.0
      - filelock==3.16.1
      - fonttools==4.55.6
      - frozenlist==1.5.0
      - huggingface-hub==0.27.1
      - idna==3.10
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iprogress==0.4
      - ipykernel==6.29.5
      - ipython==8.12.3
      - jedi==0.19.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - kiwisolver==1.4.7
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - multidict==6.1.0
      - nest-asyncio==1.6.0
      - nltk==3.9.1
      - numpy==1.24.4
      - parso==0.8.4
      - pickleshare==0.7.5
      - prompt-toolkit==3.0.50
      - propcache==0.2.0
      - psutil==6.1.1
      - pure-eval==0.2.3
      - pyarrow==15.0.0
      - pygments==2.19.1
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pywin32==308
      - pyzmq==26.2.0
      - regex==2024.11.6
      - safetensors==0.5.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - shap
      - six==1.17.0
      - stack-data==0.6.3
      - textblob==0.18.0.post0
      - tokenizers==0.20.3
      - tornado==6.4.2
      - traitlets==5.14.3
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - wcwidth==0.2.13
      - yarl==1.15.2
      - zipp==3.20.2
